on:
  # to trigger build when daily tinytex build is finished
  repository_dispatch:
    types: [daily-build]
  workflow_dispatch:

    
name: Build Daily TinyTeX Full Bundles

env:
  TINYTEX_INSTALLER: TinyTeX
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: cderv/tinytex-releases

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build Bundles For Linux

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Build TeX Live full
        run: |
          wget https://yihui.org/tinytex/TinyTeX.tar.gz
          tar xzf TinyTeX.tar.gz
          ./.TinyTeX/bin/*/tlmgr install scheme-full
          tar zcf TinyTeX-2.tar.gz .TinyTeX
          ls -lh TinyTeX*
          rm -r .TinyTeX TinyTeX.tar.gz

      - name: update daily release
        run: |
          gh release upload daily TinyTeX-2.tar.gz --clobber

  build-windows:
    runs-on: windows-latest
    name: Build Bundles For Windows

    steps:
    - name: Clone repo
      uses: actions/checkout@v3    

    - name: Build Full TinyTeX
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://yihui.org/tinytex/install-bin-windows.bat -OutFile install-bin-windows.bat
        ./install-bin-windows.bat
        & "$Env:APPDATA\TinyTeX\bin\win32\tlmgr" update --self
        & "$Env:APPDATA\TinyTeX\bin\win32\tlmgr" install scheme-full
        Compress-Archive $Env:APPDATA\\TinyTeX TinyTeX-2.zip
        gh release upload daily TinyTeX-2.zip --clobber


  build-mac:
    runs-on: macos-latest
    name: Build Bundles on Mac OS

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Build daily full version
      run: |
         curl -sL https://yihui.org/tinytex/install-bin-unix.sh | sh
         tlmgr install scheme-full || true
         tar zcf TinyTeX-2.tgz -C ~/Library TinyTeX
         gh release upload daily TinyTeX-2.tgz --clobber
